development:
  adapter: postgresql
  host: localhost
  pool: 5
  username: postgres
  password: pgpass
  database: portfolio_development

test:
  adapter: postgresql
  host: localhost
  pool: 5
  database: portfolio_test

production:
  adapter: postgresql
  database: portfolio_production
  pool: 5
  timeout: 5000
