development:
  adapter: postgresql
  host: localhost
  pool: 5
  username: ubuntu
  password: password
  database: portfolio_development

test:
  adapter: postgresql
  host: localhost
  pool: 5
  database: portfolio_test

production:
  adapter: postgresql
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: portfolio_production
  pool: 5
  timeout: 5000